#!/bin/sh

echo "*****Lint*****"
npm run lint
status=$?
if [ "$status" -ne "0" ]; then
    exit $status
fi

echo "*****Format*****"
npm run format
status=$?
if [ "$status" -ne "0" ]; then
    exit $status
fi

echo "*****Running unit tests******"

git stash -q --keep-index

npm run test-clean

status=$?

git stash pop -q

exit $status